### ISSUE TITLE
Merge time columns

### ISSUE THREAD

**Issue by jonyrock** [CorpGlory/csv2influx#11]
I have a csv dataset like this:

```
Date Of Stop,Time Of Stop, ...
08/28/2017,23:41:00, ...
```

But I need to "merge" two columns "08/28/2017,23:41:00" to "08/28/2017 23:41:00" so be able to parse it. 

I don't know how to make it better. We can something like this `"timestamp": ["Date Of Stop", "Time Of Stop"]` and concatenate two string columns to one, but it if we were able to convert one csv file to another with mapper, then it would be a solution too. Don't want to make this tool too complex.

**Comment by rozetko** [comment]
Added at https://github.com/CorpGlory/csv2influx/issues/13
