### ISSUE TITLE
Mapping name collision

### ISSUE THREAD

**Issue by jonyrock** [CorpGlory/csv2influx#12]
It's possible to make mapping like this:

```
{
  "fieldNameA": { "name": "fieldName", ... },
  "fieldNameB": { "name": "fieldName", ... },
}
```

So both fields `fieldNameA` and `fieldNameB` map to same `fieldName`. 
It should be forbidden.

**Comment by jonyrock** [comment]
@rozetko I believe we don't have this issue after "from - to swap in out config file"

**Comment by rozetko** [comment]
@jonyrock yes, but I guess we should warn user if he has two similar keys in "fieldSchema".
Eg:
```
{
  "measurementName": "traffic",
  "influxdbUrl": "http://127.0.0.1:8086/test",
  "mapping": {
    "fieldSchema": {
      "Date": {
        "from": "Date",
        "type": "timestamp",
        "format": "jsDate"
      },
      "test": {
        "from": "CO(GT)",
        "type": "string"
      },
      "test": {
        "from": "NMHC(GT)",
        "type": "string"
      }
    }
  },
  "csv": {
    "delimiter": ";"
  }
}
```

**Comment by jonyrock** [comment]
@rozetko it is not possible cuz keys in json must be unique

**Comment by rozetko** [comment]
@jonyrock I tested, node.js parses it as a valid json, keeping the last of duplicate keys. So, user can make a typo and one of fields wouldn't appear at influx.
