### ISSUE TITLE
Possibility to merge all columns

### ISSUE THREAD

**Issue by jonyrock** [CorpGlory/csv2influx#28]
Now it's possible to merge only date-related columns like this
```
"time": ["Date", "Time"]
```

It would be cool to be able merge all columns

```
"name": ["First Name", "Last Name"]
```

**Comment by lyondhill** [comment]
With merging the colums it may be useful to identify how you want them to merge. Some may want them to merge with spaces ('first_name last_name'). Some may want you to merge with commas, and others may want you to merge in a completely different way. 

Imagine a csv has Street,City,State,Zip, you may want to merge those as "Street\nCity,State\nZip".

**Comment by jonyrock** [comment]
- add tests (which fail first)
- implementation:
  - merge template
  - actual columns merge
- add an example

**Comment by jonyrock** [comment]
@lyondhill 
check this out 
```
"fieldSchema": {
      "coordinates": {
        // fields "Latitude" and "Longitude" will be concatenated 
        // with "," delimiter to create "coordinates" field
        "from": "${Latitude},${Longitude}",
        "type": "string"
      }
    },
```

Please see [examples](https://github.com/CorpGlory/csv2influx/tree/master/examples)
In version 0.12 it is now available.

P.S. How do you thing, is it worth a star here on github ? :)

**Comment by lyondhill** [comment]
I like the flexibility of interpolation. It looks really nice!
