### ISSUE TITLE
Map tags

### ISSUE THREAD

**Issue by jonyrock** [CorpGlory/csv2influx#29]
Not it's possible to map only fieldsShema, want to map tagShema as well:

```
"tagsShema": {
  "name": {
    "from": "First Name"
  }
}
```

**Comment by lyondhill** [comment]
"tagsSchema" I think.

**Comment by jonyrock** [comment]
- add tests (which fails first)
- fix examples
- implementation
- add to change logs

**Comment by jonyrock** [comment]
Hey @lyondhill 
We made it finally. 
Please, check out how https://github.com/CorpGlory/csv2influx/tree/master/examples now look like.

**Comment by lyondhill** [comment]
+1 very cool!
