### ISSUE TITLE
csv2influx fails with InfluxDB Instance with SSL/TLS

### ISSUE THREAD

**Issue by chlarsen** [CorpGlory/csv2influx#42]
First of all, a huge "Thank you" for this splendid tool.
I do have an issue: I can import the examples without any issues, if my InfluxDB runs in http mode. As soon as I switch to https, I get (using a self-signed certificate):
````
csv2influx -c ./traffic_violations.conf.json ./traffic_violations.csv
Reading ./traffic_violations.conf.json
ok
checking format
ok
lines count:96
Connecting to http://www_go.jail.vlan:8086/traffic_violations
Schema: events
Importing
Fields: {"coordinates":","}
Tags: {"agency":"MCP"}
Time: 1380035460000000000
1 BAD_WRITE
{
  "Date Of Stop": "09/24/2013",
  "Time Of Stop": "17:11:00",
  "Agency": "MCP",
  "SubAgency": "3rd district, Silver Spring",
  "Description": "DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGISTRATION",
  "Location": "8804 FLOWER AVE",
  "Latitude": "",
  "Longitude": "",
  "Accident": "No",
  "Belts": "No",
  "Personal Injury": "No",
  "Property Damage": "No",
  "Fatal": "No",
  "Commercial License": "No",
  "HAZMAT": "No",
  "Commercial Vehicle": "No",
  "Alcohol": "No",
  "Work Zone": "No",
  "State": "MD",
  "VehicleType": "02 - Automobile",
  "Year": "2008",
  "Make": "FORD",
  "Model": "4S",
  "Color": "BLACK",
  "Violation Type": "Citation",
  "Charge": "13-401(h)",
  "Article": "Transportation Article",
  "Contributed To Accident": "No",
  "Race": "BLACK",
  "Gender": "M",
  "Driver City": "TAKOMA PARK",
  "Driver State": "MD",
  "DL State": "MD",
  "Arrest Type": "A - Marked Patrol",
  "Geolocation": ""
}
Error: Parse Error
{
  "bytesParsed": 0,
  "code": "HPE_INVALID_CONSTANT"
}
````
Any thoughts? What am I missing here?
Thank you so much,
Chris

**Comment by rozetko** [comment]
Hey @chlarsen! We are glad you like this tool!
The first thing I would check - you said you have https enabled in your InfluxDB config, but in your log there is:

> Connecting to http://www_go.jail.vlan:8086/traffic_violations

Can you try switching `"influxdbUrl": "http://www_go.jail.vlan:8086/traffic_violations"` in your _traffic_violations.conf.json_ to `"influxdbUrl": "https://www_go.jail.vlan:8086/traffic_violations"`?

**Comment by chlarsen** [comment]
Greetings from Malawi,
Apologies, what you got was not the total story - my bad. I replaced https with http, because it did not work. Here is the feedback I get:
````
csv2influx -c ./traffic_violations.conf.json ./traffic_violations.csv 
Reading ./traffic_violations.conf.json
ok
checking format
ok
lines count:96
Connecting to https://www_go.jail.vlan:8086/traffic_violations
Schema: events
Importing
Fields: {"coordinates":","}
Tags: {"agency":"MCP"}
Time: 1380035460000000000
1 BAD_WRITE
{
  "Date Of Stop": "09/24/2013",
  "Time Of Stop": "17:11:00",
  "Agency": "MCP",
  "SubAgency": "3rd district, Silver Spring",
  "Description": "DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGISTRATION",
  "Location": "8804 FLOWER AVE",
  "Latitude": "",
  "Longitude": "",
  "Accident": "No",
  "Belts": "No",
  "Personal Injury": "No",
  "Property Damage": "No",
  "Fatal": "No",
  "Commercial License": "No",
  "HAZMAT": "No",
  "Commercial Vehicle": "No",
  "Alcohol": "No",
  "Work Zone": "No",
  "State": "MD",
  "VehicleType": "02 - Automobile",
  "Year": "2008",
  "Make": "FORD",
  "Model": "4S",
  "Color": "BLACK",
  "Violation Type": "Citation",
  "Charge": "13-401(h)",
  "Article": "Transportation Article",
  "Contributed To Accident": "No",
  "Race": "BLACK",
  "Gender": "M",
  "Driver City": "TAKOMA PARK",
  "Driver State": "MD",
  "DL State": "MD",
  "Arrest Type": "A - Marked Patrol",
  "Geolocation": ""
}
Error: unable to verify the first certificate
{
  "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
}
````
Ye,s I do use a self-signed certificate. This may be the reason for this failure, but there should be a work-around?
Any thoughts?
Thank you so much.
Chris

**Comment by rozetko** [comment]
@chlarsen hi again! I tested it on my PC and getting the same error.

I researched this issue and found that developers of lib that we use recommend using free [letsencrypt](https://letsencrypt.org/) certificate instead of self-signed one.

Actually, there is a work around, but you should understand that there is no sense in using HTTPS in this case.
Just set environment variable _NODE_TLS_REJECT_UNAUTHORIZED_ to _0_. 
Example for Linux:
`export NODE_TLS_REJECT_UNAUTHORIZED=0`

You can read more about this issue here: https://github.com/node-influx/node-influx/issues/117

**Comment by chlarsen** [comment]
That fixed it (as in work around). Thank you so much, as implementing Letsencryt on an InfluxDB instance is a it of a pain!
Cheers!
Chris

**Comment by jonyrock** [comment]
Hey guys, should we close this issue?

**Comment by chlarsen** [comment]
I think so, thank you so much! Unless you want me to post my highly primitive wrapper :-)

On February 3, 2018 3:08:28 PM UTC, Alexey Velikiy <notifications@github.com> wrote:
>Hy guys, should we close this issue? 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/CorpGlory/csv2influx/issues/42#issuecomment-362819676

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
