### ISSUE TITLE
InfluxDB auth

### ISSUE THREAD

**Issue by rozetko** [CorpGlory/csv2influx#44]
We need to add authorization support

**Comment by jonyrock** [comment]
One possible workaround: remove password from influx and try to import. Than set your password back 
![image](https://user-images.githubusercontent.com/1022757/37875798-a04b9fae-304c-11e8-9277-682b7fe9f92f.png)

**Comment by jonyrock** [comment]
Use this to connect to DB: `influxdbUrl` in config
`http://user:pass@localhost:port,anotherhost:port,yetanother:port/mydatabase`
