### ISSUE TITLE
import without timestamp

### ISSUE THREAD

**Issue by jonyrock** [CorpGlory/csv2influx#6]
There is a 
```
"mapping": {
    "timestamp": "Date",
    .....
```

in `csv2influx.conf.json` . I wand to be allowed to import data without `timestamp` param

**Comment by rozetko** [comment]
@jonyrock issue is still actual, I guess

**Comment by jonyrock** [comment]
Well, yes. We can reopen it. The problem is that I don't know which strategy to use here.
We can show warning if date is missing

**Comment by rozetko** [comment]
@jonyrock actually, warning is what I was going to show :+1:

**Comment by jonyrock** [comment]
@rozetko I close it now
